### ISSUE TITLE
PHP 7.4 support?

### ISSUE THREAD

**Issue by bilogic** [tonysm/importmap-laravel#15]
Hi,

Possible to support PHP7.4?

**Comment by tonysm** [comment]
Hey, sorry, but looks like PHP 7.4 is no longer in active development, and only has 4 months of security updates. It's not worth it, imo.

**Comment by bilogic** [comment]
Thanks and sure, I respect your decision.

It could be worth the traction since 7.4 still commands the lead https://stitcher.io/blog/php-version-stats-january-2022

**Comment by tonysm** [comment]
You're probably right. That stats is probably overall PHP usage, I wish there was a PHP version stats for Laravel users, which I'd bet are more on PHP 8 (since Laravel 9 requires PHP 8+).

Looking at the download stats for `laravel/framework`, I see that Laravel 8 still leads the installs and that supports PHP 7.3 through PHP 8 ([source](https://packagist.org/packages/laravel/framework/stats)), so there's something there:

<img width="785" alt="image" src="https://user-images.githubusercontent.com/1178621/176258800-e4f420dd-b4ec-420a-83fd-16f6f3197d63.png">

Although I still think there might be more Laravel 8 installs running on PHP 8 than 7.4, I have no data to back this up. Also, Laravel 9 is quickly catching up, which indicates it will soon pass Laravel 8 daily installs, so... don't know.

I'll try running the test suite against PHP 7.4 and see how much work would be to back-port it, but won't promise I'll make it. Still don't think it's worth it. ;)
