### ISSUE TITLE
npm command 

### ISSUE THREAD

**Issue by odion-cloud** [tonysm/importmap-laravel#6]
npm command no longer working

**Comment by tonysm** [comment]
Which NPM command? There's no NPM command for this package. In fact, it aims to get rid of NPM whatsoever.

**Comment by odion-cloud** [comment]
not this package but node_mudule packages, how do i install new npm packages 
like npm install <packagename> or any other way out with this package

**Comment by tonysm** [comment]
With this package, you won't need NPM. This assumes you're writing frontend code that doesn't need transpilation or bundling. You could pair this package up with Stimulus.js or Alpine.js, for instance.

Instead of running:

```bash
npm install --save alpinejs
```

You would use the pin command:

```bash
php artisan importmap:pin alpinejs
```

This would be enough. Make sure you read the docs ([README](https://github.com/tonysm/importmap-laravel)) and check out [this video](https://youtu.be/3P_h7zWY1pU) if you want to see this in action.

**Comment by odion-cloud** [comment]
wow this means i can delete my node module folder with a lot of lib in it?
